### ISSUE TITLE
LedFX Remote constantly writing to logs and processor running at 25%

### ISSUE THREAD

**Issue by pjbpaul** [YeonV/ledfxrm#5]
Hi,
I have LedFX running on a raspberry pi 3B+ that has a usb mic to listen for music. I have 2 dig-uno running WLED version 0.11.1 (latest) and all works great. I am running Home Assistant supervised 2021.01.5 (latest) on core-2021.1.4 (latest) on a ESXI virtual machine. When I install LedFx Remote 0.2.4 (latest) through Hacs 1.10.0 (latest) I'm getting log and performance problems. The processor jumps from 7% normal running to 25%. Then LedFx Controller is writing over 1 million logs per hour to the logfile. Below is the log, IP addresses are correct but replaced by XXXXXX. The logs are been written even without any led Scenes selected. 

UPDATING WTF {'info': {'url': 'http://0.0.0.0:8888', 'name': 'LedFx Controller', 'version': '0.9.2', 'debug_mode': True}, 'devices': {'status': 'success', 'devices': {'wled-2': {'config': {'center_offset': 0, 'channel_count': 180, 'channel_offset': 0, 'force_refresh': False, 'ip_address': '192.XXXXXXX', 'max_brightness': 1.0, 'name': 'wled-2', 'pixel_count': 60, 'preview_only': False, 'refresh_rate': 60, 'universe': 1, 'universe_end': 1, 'universe_size': 512, 'type': 'e131'}, 'id': 'wled-2', 'type': 'e131', 'effect': {}}, 'wled-1': {'config': {'center_offset': 0, 'channel_count': 180, 'channel_offset': 0, 'force_refresh': False, 'ip_address': '192.XXXXXX', 'max_brightness': 1.0, 'name': 'wled-1', 'pixel_count': 60, 'preview_only': False, 'refresh_rate': 60, 'universe': 1, 'universe_end': 1, 'universe_size': 512, 'type': 'e131'}, 'id': 'wled-1', 'type': 'e131', 'effect': {}}}}, 'virtuals': {'virtuals': {'blade': True, 'list': []}}, 'scenes': {'status': 'success', 'scenes': {'wled-2-bar': {'devices': {'wled-2': {'config': {'background_color': 'black', 'blur': 0.0, 'brightness': 1.0, 'color_step': 0.327, 'ease_method': 'ease_out', 'flip': False, 'gradient_name': 'Rainbow', 'gradient_repeat': 1, 'gradient_roll': 0, 'mirror': False, 'mode': 'bounce'}, 'type': 'bar(Reactive)'}}, 'name': 'wled-2 Bar'}, 'wled-2-off': {'devices': {'wled-1': {}, 'wled-2': {}}, 'name': 'wled-2 Off'}, 'wled-2-rain-sensitive': {'devices': {'wled-2': {'config': {'background_color': 'black', 'blur': 0.0, 'brightness': 1.0, 'flip': False, 'high_colour': 'blue', 'high_sensitivity': 0.035, 'lows_colour': 'white', 'lows_sensitivity': 0.03, 'mids_colour': 'red', 'mids_sensitivity': 0.03, 'mirror': True, 'raindrop_animation': 'droplet_0.npy'}, 'type': 'rain(Reactive)'}}, 'name': 'wled-2 Rain Sensitive'}, 'wled-2-real-strobe': {'devices': {'wled-2': {'config': {'background_color': 'black', 'bass_strobe_decay_rate': 0.5, 'bass_threshold': 0.4, 'blur': 0.0, 'brightness': 1.0, 'color_step': 0.0625, 'flip': False, 'gradient_name': 'Dancefloor', 'gradient_repeat': 1, 'gradient_roll': 0, 'mirror': False, 'strobe_color': 'white', 'strobe_decay_rate': 0.5, 'strobe_width': 10}, 'type': 'real_strobe(Reactive)'}}, 'name': 'wled-2 Real Strobe'}}}, 'show_subdevices': False}

When a scene is selected this is the logs 

UPDATING WTF {'info': {'url': 'http://0.0.0.0:8888', 'name': 'LedFx Controller', 'version': '0.9.2', 'debug_mode': True}, 'devices': {'status': 'success', 'devices': {'wled-2': {'config': {'center_offset': 0, 'channel_count': 180, 'channel_offset': 0, 'force_refresh': False, 'ip_address': '192.XXXXXXXX', 'max_brightness': 1.0, 'name': 'wled-2', 'pixel_count': 60, 'preview_only': False, 'refresh_rate': 60, 'universe': 1, 'universe_end': 1, 'universe_size': 512, 'type': 'e131'}, 'id': 'wled-2', 'type': 'e131', 'effect': {'config': {'background_color': 'black', 'blur': 0.0, 'brightness': 1.0, 'flip': False, 'high_colour': 'blue', 'high_sensitivity': 0.035, 'lows_colour': 'white', 'lows_sensitivity': 0.03, 'mids_colour': 'red', 'mids_sensitivity': 0.03, 'mirror': True, 'raindrop_animation': 'droplet_0.npy'}, 'name': 'Rain', 'type': 'rain(Reactive)'}}, 'wled-1': {'config': {'center_offset': 0, 'channel_count': 180, 'channel_offset': 0, 'force_refresh': False, 'ip_address': '192.168.0.126', 'max_brightness': 1.0, 'name': 'wled-1', 'pixel_count': 60, 'preview_only': False, 'refresh_rate': 60, 'universe': 1, 'universe_end': 1, 'universe_size': 512, 'type': 'e131'}, 'id': 'wled-1', 'type': 'e131', 'effect': {}}}}, 'virtuals': {'virtuals': {'blade': True, 'list': []}}, 'scenes': {'status': 'success', 'scenes': {'wled-2-bar': {'devices': {'wled-2': {'config': {'background_color': 'black', 'blur': 0.0, 'brightness': 1.0, 'color_step': 0.327, 'ease_method': 'ease_out', 'flip': False, 'gradient_name': 'Rainbow', 'gradient_repeat': 1, 'gradient_roll': 0, 'mirror': False, 'mode': 'bounce'}, 'type': 'bar(Reactive)'}}, 'name': 'wled-2 Bar'}, 'wled-2-off': {'devices': {'wled-1': {}, 'wled-2': {}}, 'name': 'wled-2 Off'}, 'wled-2-rain-sensitive': {'devices': {'wled-2': {'config': {'background_color': 'black', 'blur': 0.0, 'brightness': 1.0, 'flip': False, 'high_colour': 'blue', 'high_sensitivity': 0.035, 'lows_colour': 'white', 'lows_sensitivity': 0.03, 'mids_colour': 'red', 'mids_sensitivity': 0.03, 'mirror': True, 'raindrop_animation': 'droplet_0.npy'}, 'type': 'rain(Reactive)'}}, 'name': 'wled-2 Rain Sensitive'}, 'wled-2-real-strobe': {'devices': {'wled-2': {'config': {'background_color': 'black', 'bass_strobe_decay_rate': 0.5, 'bass_threshold': 0.4, 'blur': 0.0, 'brightness': 1.0, 'color_step': 0.0625, 'flip': False, 'gradient_name': 'Dancefloor', 'gradient_repeat': 1, 'gradient_roll': 0, 'mirror': False, 'strobe_color': 'white', 'strobe_decay_rate': 0.5, 'strobe_width': 10}, 'type': 'real_strobe(Reactive)'}}, 'name': 'wled-2 Real Strobe'}}}, 'show_subdevices': False}

I don't have anything for LedFX Remote in my configuration.yaml file.

I completely removed LedFX, rebooted and all was ok, I  reinstalled it again and get the same problems. Any ideas or thoughts would be greatly appreciated.

Thanks

**Comment by YeonV** [comment]
Hey thanks!!
Should be fixed in v0.2.5
